import React from 'react'

export default function SkillsSection() {
  return (
    <section id='skills'>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis vel harum voluptatum sit a natus tempore dicta aperiam voluptates placeat nostrum similique, aliquid consequuntur, maxime doloribus numquam magni modi beatae eius expedita dolore. Cupiditate ipsa dolore rerum suscipit a, adipisci consequuntur, tenetur dolor autem odio fuga mollitia ex alias laudantium excepturi ipsam animi hic esse incidunt fugit, quia vitae omnis officiis laboriosam? Officia blanditiis in nemo voluptates, hic eveniet nulla, sint cumque corporis ipsum itaque molestias quae optio adipisci officiis explicabo suscipit. Reprehenderit ad magni pariatur enim debitis, explicabo culpa rerum nisi temporibus recusandae dignissimos reiciendis eveniet, hic atque vel? Similique, quisquam nesciunt quod dolorem earum impedit fugit, officiis repudiandae, quas perferendis iste consequatur numquam sint magni vel? Ab sed ad neque iure adipisci eos temporibus eaque modi molestias minus fugiat, ex dolorem officia architecto, consequuntur laboriosam distinctio esse? Dolor magnam animi, minima dignissimos perferendis saepe! Aliquam obcaecati, quis itaque reprehenderit, modi numquam nostrum sapiente odio earum veritatis et. Praesentium sed quaerat accusamus rem consectetur voluptatibus facilis nostrum doloremque dolore, qui et explicabo similique quidem ipsa itaque quisquam non dicta reprehenderit debitis sunt minus earum! Autem dignissimos cupiditate sapiente nemo quibusdam natus eius, architecto iusto quos, debitis nostrum ipsum eaque voluptas ullam similique nisi. Voluptatem expedita autem earum eligendi, numquam doloremque et amet facere ducimus illum fuga repellat sit nisi impedit dignissimos natus iusto harum vel ut, doloribus eaque deserunt. Ullam sapiente iure natus repudiandae sint, consectetur corporis quia delectus eligendi nulla porro vero voluptatem ex! Amet aperiam repudiandae saepe, odio tempora eos assumenda vitae non dignissimos. Dolores odit, quisquam delectus nemo nobis natus saepe esse id nulla, laboriosam exercitationem culpa possimus error tempora cupiditate unde. Adipisci ratione minima dolorem totam perferendis quod numquam assumenda dignissimos praesentium sequi quibusdam, explicabo quos sint. Adipisci suscipit sunt maiores excepturi earum officia at!
    </section>
  )
}
